## Introduction to **NumPy**

## What is NumPy?
NumPy (Numerical Python) is an open-source Python library used for numerical computations and working with large multidimensional arrays and matrices.

### It provides:
    1. Fast array operations
    2. Mathematical functions
    3. Linear algebra tools
    4. Random number generation
    5. Statistical functions
### NumPy forms the foundation of many libraries such as:
    1. Pandas
    2. Scikit-Learn
    3. TensorFlow
    4. PyTorch
    5. SciPy
    6. OpenCV

## Why NumPy was **Developed**?

#### Python lists were:
    1. Slow
    2. Memory inefficient
    3. Not suitable for large numerical computations
### NumPy was developed to:
    1. Perform high-speed mathematical calculations
    2. Store large datasets efficiently
    3. Support matrix operations
    4. Provide vectorized computations

## Need for NumPy
    Suppose we want to MULTIPLY two lists.

In [ ]:
a = [2,4,5,6]
b = [4,6,7,8]

import time
start = time.time()
result =[]
for i in range(len(a)):
    result.append(a[i]*b[i])
print(time.time()-start)
print(result)

In [ ]:
import numpy as np

In [ ]:
a = np.array([2,4,5,6])
b = np.array([4,6,7,8])
start = time.time()
c = a*b
print(time.time()-start)
print(c)

## How to install **NumPy**

NumPy is not a built-in Python library; you must install it within your environment

In [ ]:
!pip install numpy

## Import the NumPY

import numpy
##### or
import numpy as np
###### or
# **import numpy as any_alias_name:*
    Example: import numpy as hy       , 
         import numpy as npy

In [ ]:
import numpy as qwert

In [ ]:
a = qwert.array([4,6,8])

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [ ]:
import numpy as np

arr = np.array([2,3,4,5])
print(arr)

In [ ]:
type(arr)

In [ ]:
arr = np.array([2,3,'run',6])

In [ ]:
print(arr)

here you can perform addition -> concatenation
* --> NUMBER OF TIMES arr*2= [22,33,runrun,66]

In [ ]:
arr = np.array([2,3,89,6], dtype =np.int32 )


In [ ]:
arr

In [ ]:
arr = np.array([2,3,89,6], dtype =np.int64 )
arr

In [ ]:
arr = np.array([2,3,89,6,'run'], dtype =np.int32 )

In [ ]:
help(np.array)

*array contain homogeneous data type*

In [179]:
arr = np.array([3.5,6.78,98.567,89])

In [180]:
arr

array([ 3.5  ,  6.78 , 98.567, 89.   ])

In [181]:
arr = np.array([4,5,6,7,8], dtype=np.float32)

In [182]:
arr

array([4., 5., 6., 7., 8.], dtype=float32)

In [183]:
arr = np.array([4,5,6,7,'ertyu',8], dtype=np.float32)


ValueError: could not convert string to float: 'ertyu'

In [184]:
arr = np.array([3.5,6.78,98.567,89], dtype = np.int32)
arr

array([ 3,  6, 98, 89], dtype=int32)

In [186]:
arr = np.array([True,False, True, True])
arr

array([ True, False,  True,  True])

In [187]:
arr = np.array([1,3,4,0,8,0], dtype = np.bool)
arr

array([ True,  True,  True, False,  True, False])

## 0-D Arrays
    0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.



In [188]:
a = np.array(34)

In [190]:
print(a)
print(type(a))

34
<class 'numpy.ndarray'>


## 1-D Arrays
    An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [191]:
oneDarray = np.array([3,4,5,7,78]) # 1x5

In [192]:
oneDarray

array([ 3,  4,  5,  7, 78])

## 2-D Arrays
    An array that has 1-D arrays as its elements is called a 2-D array.

    These are often used to represent matrix or 2nd order tensors.

In [193]:
d2_array = np.array(
    [
       [2,6],
        [5,9],
        [8,7]
    ]
)

In [194]:
print(d2_array)

[[2 6]
 [5 9]
 [8 7]]


## 3-D arrays
    An array that has 2-D arrays (matrices) as its elements is called 3-D array.

    These are often used to represent a 3rd order tensor.

In [195]:
d3arr = np.array(

    [
    [[44,55],[67,89]],
    [[67,78],[89,67]]
        
    ]
)

In [196]:
d3arr

array([[[44, 55],
        [67, 89]],

       [[67, 78],
        [89, 67]]])

In [197]:
ar  = np.array([[[45,67]]])

In [198]:
ar

array([[[45, 67]]])

## Cheeck Number of Dimensions?
    NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [199]:
print(oneDarray.ndim)

1


In [200]:
print(d2_array.ndim)

2


In [201]:
d3arr.ndim

3

## Higher Dimensional Arrays
    An array can have any number of dimensions.

    When the array is created, you can define the number of dimensions by using the ndmin argument.

In [205]:
arr = np.array([1,2,3,4,5,6,7],ndmin=7)
print(arr)
print(arr.ndim)

[[[[[[[1 2 3 4 5 6 7]]]]]]]
7


##  different other ways to check dimensions

1. ndim
2. shape
3. size

In [206]:
print(oneDarray.ndim)
print(oneDarray.size)
print(oneDarray.shape)


1
5
(5,)


In [207]:
d2_array = np.array(
    [
       [2,6],
        [5,9],
        [8,7]
    ]
)

In [208]:
print(d2_array.ndim)
print(d2_array.size)
print(d2_array.shape)


2
6
(3, 2)


## **Note**:
    ndim → Number of dimensions
    shape → Structure of the array
    size → Total number of elements

## Access Array Elements

In [209]:
a = [[3,5,6,7,8], [5673.75798,989,76,766,6]]

In [211]:
a[1][2]

76

In [218]:
a = np.array([[3,5,6,7,8], [5673.75798,989,76,766,6]])

In [214]:
print(a[0,1])
print(a[0][1])

5.0
5.0


In [219]:
print(a[1,-1])

6.0


In [215]:
a = np.array([[[2,3,4,5],[4,6,7,7]]])

In [216]:
print(a[0,0,0])

2


## NumPy Array Slicing

In [ ]:
a[:3], a[::-1]

## Data Types in NumPy

#### NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

    Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )

In [220]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [221]:
arr = np.array(['a','b','c','d'])
arr.dtype

dtype('<U1')

## Creating Arrays With a Defined Data Type

In [222]:
arr = np.array([1,2,3,4], dtype ='S')
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [225]:
arr = np.array([1,2,3,4], dtype ='i4')
arr

array([1, 2, 3, 4], dtype=int32)

# conversion of data type

**The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.**

In [229]:
arr= np.array([3.4,5.6,7.8,9.0])
arr

array([3.4, 5.6, 7.8, 9. ])

In [227]:
converted_arr = arr.astype('i')

In [228]:
converted_arr

array([3, 5, 7, 9], dtype=int32)

In [230]:
converted_arr_int = arr.astype('int')


In [231]:
converted_arr_int

array([3, 5, 7, 9])

In [232]:
bool_conv = arr.astype('bool')

In [233]:
bool_conv

array([ True,  True,  True,  True])

## NumPy Array Copy vs View


### **Copy vs View in NumPy**

1. **Copy creates a new array**, while **View refers to the original array**.
2. **Copy has its own data**, so changes in the copy do **not** affect the original array.
3. **Changes in the original array do not affect the copy**.
4. **View shares the data with the original array**.
5. **Changes in the view affect the original array**.
6. **Changes in the original array also affect the view**.

### Shortcut to Remember

* **Copy → Independent data → No effect on original**
* **View → Shared data → Changes affect both**


In [234]:
a = np.array([2,3,5])
b = a.copy()

In [235]:
a , b

(array([2, 3, 5]), array([2, 3, 5]))

In [238]:
b[0] = 1111134567

In [239]:
a , b

(array([34567,     3,     5]), array([1111134567,          3,          5]))

In [241]:
a = np.array([2,3,5])
b = a.view()
a,b

(array([2, 3, 5]), array([2, 3, 5]))

In [242]:
a[1] = 4567

In [243]:
a,b

(array([   2, 4567,    5]), array([   2, 4567,    5]))

In [244]:
b[0] = 56789765456

In [245]:
a,b

(array([56789765456,        4567,           5]),
 array([56789765456,        4567,           5]))

### **Checking Data Ownership in NumPy**

1. Every NumPy array has a **`base` attribute**.
2. If **`base` returns `None`**, the array **owns its data** (it is a **copy**).
3. If **`base` returns another array**, the array **does not own its data** (it is a **view**).
4. A **copy is independent**, while a **view shares data with the original array**.



In [246]:
a = np.array([2,3,5])
b_view = a.view()
c_copy = a.copy()

print(a)
print(b_view)
print(c_copy)


[2 3 5]
[2 3 5]
[2 3 5]


In [247]:
print(a.base)
print(b_view.base)
print(c_copy.base)

None
[2 3 5]
None


## NumPy Array Reshaping

### **Reshaping Arrays in NumPy**

1. **Reshaping means changing the shape of an array.**
2. **The shape of an array tells the number of elements in each dimension.**
3. **Reshaping can change the number of rows and columns.**
4. **Reshaping can add or remove dimensions.**
5. **The total number of elements must remain the same after reshaping.**


## **Reshape From 1-D to 2-D*

In [248]:
aa = np.array([1,2,43,5,6,7,8,9,0])
aa.shape

(9,)

In [250]:
reshaped_arr = aa.reshape(3,3)

In [251]:
reshaped_arr

array([[ 1,  2, 43],
       [ 5,  6,  7],
       [ 8,  9,  0]])

In [252]:
reshaped_arr = aa.reshape(2,5)

ValueError: cannot reshape array of size 9 into shape (2,5)

In [253]:
aa = np.array([1,2,43,5,6,7,8,9,0,3,4,5])
aa.shape

(12,)

In [255]:
reshaped_arr = aa.reshape(2,6)
reshaped_arr

array([[ 1,  2, 43,  5,  6,  7],
       [ 8,  9,  0,  3,  4,  5]])

In [256]:
reshaped_arr = aa.reshape(4,3)
reshaped_arr

array([[ 1,  2, 43],
       [ 5,  6,  7],
       [ 8,  9,  0],
       [ 3,  4,  5]])

In [257]:
reshaped_arr = aa.reshape(4,4)
reshaped_arr

ValueError: cannot reshape array of size 12 into shape (4,4)

## **Reshape From 1-D to 3-D*

In [264]:
aa = np.array([1,2,43,5,6,7,8,9,0,3,4,5])
aa.shape

(12,)

In [259]:
aa.reshape(2,3,2)

array([[[ 1,  2],
        [43,  5],
        [ 6,  7]],

       [[ 8,  9],
        [ 0,  3],
        [ 4,  5]]])

In [261]:
aa = np.array([1,2,43,5,6,7,8,9])
aa.shape

(8,)

In [262]:
aa.reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

### **Unknown Dimension in NumPy**

1. **NumPy allows one unknown dimension while reshaping.**
2. **Use `-1` to represent the unknown dimension.**
3. **NumPy automatically calculates the value of the unknown dimension.**
4. **Only one dimension can be specified as `-1`.**
5. **The total number of elements remains unchanged.**

### NOte

* **`-1` → Unknown dimension**
* **NumPy calculates it automatically**
* **Only one `-1` is allowed**


In [260]:
aa.reshape(2,3,-1) # 2*3*2


array([[[ 1,  2],
        [43,  5],
        [ 6,  7]],

       [[ 8,  9],
        [ 0,  3],
        [ 4,  5]]])

In [265]:
aa.reshape(2,-1,3) # 2 * 3 *2


array([[[ 1,  2, 43],
        [ 5,  6,  7]],

       [[ 8,  9,  0],
        [ 3,  4,  5]]])

# Flattening the arrays (Important in deep learning)
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [266]:
a = np.array([[[ 1,  2, 43],
        [ 5,  6,  7]],

       [[ 8,  9,  0],
        [ 3,  4,  5]]])

In [267]:
a

array([[[ 1,  2, 43],
        [ 5,  6,  7]],

       [[ 8,  9,  0],
        [ 3,  4,  5]]])

In [268]:
a.reshape(-1)

array([ 1,  2, 43,  5,  6,  7,  8,  9,  0,  3,  4,  5])

## **Functions for Changing and Rearranging Arrays in NumPy*

These functions belong to the Intermediate to Advanced section of NumPy.

1. flatten()
    1. Converts a multidimensional array into a 1D array.
    2. Returns a copy of the original array.
    3. Changes made to the flattened array do not affect the original array.

In [269]:
aw= a.flatten()

array([ 1,  2, 43,  5,  6,  7,  8,  9,  0,  3,  4,  5])

2. ravel()
    1. Converts a multidimensional array into a 1D array.
    2. Returns a view of the original array whenever possible.
    3. Changes may affect the original array.

In [277]:
a.ravel()

array([ 3,  4,  5,  6,  3, 45, 56,  6])

3. flip()
    1. Reverses elements along specified axes.

In [278]:
arr = np.array([[1,2,3],[4,5,6]])

In [280]:
np.flip(arr)

array([[6, 5, 4],
       [3, 2, 1]])

In [281]:
np.fliplr(arr)

array([[3, 2, 1],
       [6, 5, 4]])

In [282]:
np.flipud(arr)

array([[4, 5, 6],
       [1, 2, 3]])

In [285]:
np.rot90(arr)

array([[3, 6],
       [2, 5],
       [1, 4]])

# How to add the elements in a numpy array

In [18]:
import numpy as np


In [19]:
arr = np.array([])

In [20]:
arr

array([], dtype=float64)

In [21]:
arr.append(23) ## not valid becoz we are numpy array

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [22]:
arr = []
arr.append(23)
arr

[23]

In [23]:
arr = np.array([])
arr

array([], dtype=float64)

In [24]:
np.append(arr,[34])

array([34.])

In [25]:
print(arr)

[]


In [26]:
arr = np.append(arr,[34])


In [27]:
print(arr)

[34.]


In [28]:
arr = np.append(arr,[3,45,4,66,3,44])
arr

array([34.,  3., 45.,  4., 66.,  3., 44.])

In [29]:
a = np.array([2,3,4])

In [31]:
b = np.append(a,[6666])

In [33]:
# 
print(a.base)
print(b.base)

None
None


In [32]:
print(a)
print(b)

[2 3 4]
[   2    3    4 6666]


# user input data for an array

In [38]:
a = np.array([], dtype = np.int32)

In [39]:
no_of_element = int(input('No. of elements you want to insert: '))

No. of elements you want to insert:  3


In [40]:
for i in range(no_of_element):
    a = np.append(a, int(input('Enter element: ')))
print(a)

Enter element:  3
Enter element:  4
Enter element:  5


[3 4 5]


In [47]:
def create_array(a,n):
    if n == 0:
        return a
    a = np.append(a, int(input('Enter element: ')))
    
    return create_array(a,n-1)

a = np.array([]) 
no_of_element = int(input('No. of elements you want to insert: '))
print(create_array(a,no_of_element))

No. of elements you want to insert:  3
Enter element:  34
Enter element:  56
Enter element:  67


[34. 56. 67.]


array([], dtype=float64)

### **Iterating Arrays in NumPy**

1. **Iterating means accessing array elements one by one.**
2. **NumPy arrays can be iterated using Python's `for` loop.**
3. **For a 1D array, iteration goes through each element one by one.**
4. **Multi-dimensional arrays can also be iterated using loops.**

In [50]:
a = np.array([1,2,4,5,76,8,9,6,4,2])
for i in range(len(a)):
    print(a[i], end = " / ")


1 / 2 / 4 / 5 / 76 / 8 / 9 / 6 / 4 / 2 / 

In [51]:
for ele in a:
    print(ele)

1
2
4
5
76
8
9
6
4
2


## Iterating 2-D Arrays
In a 2-D array it will go through all the rows.

In [52]:
a = np.array([[23,45,66],[44,56,77]])

In [56]:
for i in range(2):
    for j in range(3):
        print(a[i][j])
        print("......")

23
......
45
......
66
......
44
......
56
......
77
......


In [60]:
a = np.array([[23,45,66,5,6,6],[44,56,77,8,9,4]])

# to find no. of rows and columns

In [57]:
print(len(a)) # no of rows

2


In [58]:
print(len(a[0]))

3


In [63]:
for i in range(len(a)):
    for j in range(len(a[0])):
        print(a[i][j])
        print("......")

23
......
45
......
66
......
5
......
6
......
6
......
44
......
56
......
77
......
8
......
9
......
4
......


In [65]:
a = np.array([[1,2,3],[5,6]])



ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [66]:
a =[[3,4,5],[1,2]]

In [72]:
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j])
       

3
4
5
1
2


In [73]:
a = np.array([[23,45,66,5,6,6],[44,56,77,8,9,4]])


In [75]:
for val in a:
    for ele in val:
        print(ele)

23
45
66
5
6
6
44
56
77
8
9
4


# Assignment 

### **access the elements of 3d array*

### **Iterating Arrays Using `nditer()`**

1. **`nditer()` is a function used for easy array iteration.**
2. **It can handle both simple and advanced iterations.**
3. **`nditer()` accesses each scalar element one by one.**
4. **It simplifies iteration for multi-dimensional arrays.**
5. **Using `nditer()`, we do not need multiple nested `for` loops.**

### Note:

* **`nditer()` → Easy iteration**
* **Visits each element one by one**
* **Useful for high-dimensional arrays**
* **Avoids writing many nested loops**


In [76]:
a = np.array([[23,45,66,5,6,6],[44,56,77,8,9,4]])


In [77]:
for val in np.nditer(a):
    print(val)

23
45
66
5
6
6
44
56
77
8
9
4


In [78]:
a = np.array([[[23,45,66],[5,6,6]],[[44,56,77],[8,9,4]]])
for val in np.nditer(a):
    print(val)

23
45
66
5
6
6
44
56
77
8
9
4


### **Iterating Arrays with Different Data Types**

1. **`op_dtypes` is used to specify the desired data type while iterating.**
2. **NumPy does not change the original array elements directly.**
3. **It uses extra temporary memory called a buffer to store converted values.**
4. **To enable this buffer, use `flags=['buffered']` with `nditer()`.**
5. **This allows iteration with a different data type without modifying the original array.**

### Short Note

* **`op_dtypes` → Change data type during iteration**
* **Original array remains unchanged**
* **Buffer = Temporary memory**
* **Use `flags=['buffered']` to enable the buffer**


In [79]:
a = np.array([2,4,5])
a

array([2, 4, 5])

In [80]:
for val in np.nditer(a, flags=['buffered'], op_dtypes=['S']):
    print(val)

np.bytes_(b'2')
np.bytes_(b'4')
np.bytes_(b'5')


### **Enumerated Iteration Using `ndenumerate()`**

1. **Enumeration means accessing elements along with their index.**
2. **`ndenumerate()` is used to iterate through arrays with index values.**
3. **It returns both the index and the corresponding element.**
4. **It is useful when we need the position of each element during iteration.**
5. **It works with arrays of any dimension.**



In [81]:
a = np.array([[2,3,4],[5,6,7]])
for index, val in np.ndenumerate(a):
    print(f"index : {index} and value: {val}")


index : (0, 0) and value: 2
index : (0, 1) and value: 3
index : (0, 2) and value: 4
index : (1, 0) and value: 5
index : (1, 1) and value: 6
index : (1, 2) and value: 7


## NumPy Joining Array

### **Joining Arrays in NumPy**

1. **Joining means combining two or more arrays into a single array.**
2. **NumPy joins arrays based on axes.**
3. **The `concatenate()` function is used to join arrays.**
4. **Multiple arrays are passed as a sequence to `concatenate()`.**
5. **The `axis` parameter specifies along which axis the arrays are joined.**
6. **If `axis` is not specified, NumPy uses `axis=0` by default.**

### Remember

* **Joining = Combining arrays**
* **Use `concatenate()`**
* **Join is done along an axis**
* **Default axis = 0**


In [84]:
a1 = np.array([1,2,3])
a2 = np.array([11,21,33])
arr = np.concatenate((a2,a1))
arr

array([11, 21, 33,  1,  2,  3])

In [90]:
arr = np.concatenate((a2,a1), axis = 0)
arr

array([[11, 21],
       [33, 55],
       [ 1,  2],
       [ 3, 99]])

## Join two 2-D arrays along rows (axis=1)

In [85]:
a1 = np.array([[1,2],[3,99]])
a2 = np.array([[11,21],[33,55]])

In [87]:
arr = np.stack((a1,a2))
arr

array([[[ 1,  2],
        [ 3, 99]],

       [[11, 21],
        [33, 55]]])

In [88]:
arr = np.stack((a1,a2), axis =1)
arr

array([[[ 1,  2],
        [11, 21]],

       [[ 3, 99],
        [33, 55]]])

### **Joining Arrays Using Stack Functions**

1. **Stacking is similar to concatenation, but it creates a new axis.**
2. **The `stack()` function is used to stack arrays.**
3. **Stacking combines arrays one above the other or side by side along a new dimension.**
4. **Multiple arrays are passed as a sequence to `stack()`.**
5. **The `axis` parameter specifies the new axis along which arrays are stacked.**
6. **If `axis` is not specified, NumPy uses `axis=0` by default.**



* **Stacking = Concatenation + New Axis**


### Stacking Along Rows
use hstack() to stack along rows.

In [92]:
a1 = np.array([1,2,3,99])
a2 = np.array([11,21,33,55])
arr = np.hstack((a1,a2))

In [93]:
arr

array([ 1,  2,  3, 99, 11, 21, 33, 55])

## Stacking Along Columns
use vstack()  to stack along columns.

In [94]:
arr = np.vstack((a1,a2))


In [95]:
arr

array([[ 1,  2,  3, 99],
       [11, 21, 33, 55]])

## Stacking Along Height (depth)
use dstack() to stack along height, which is the same as depth.

In [96]:
arr = np.dstack((a1,a2))
arr

array([[[ 1, 11],
        [ 2, 21],
        [ 3, 33],
        [99, 55]]])

### **Splitting NumPy Arrays**

1. **Splitting is the opposite of joining.**
2. **Joining combines multiple arrays into one array.**
3. **Splitting divides one array into multiple arrays.**
4. **The `array_split()` function is used to split arrays.**
5. **Pass the array and the number of splits to `array_split()`.**

### Notesz

* **Joining → Many arrays → One array**
* **Splitting → One array → Many arrays**
* **Use `array_split()` for splitting**


In [97]:
arr = np.array([1,2,4,5,6,7,8,9])
splitted_array = np.array_split(arr,3)

In [98]:
splitted_array

[array([1, 2, 4]), array([5, 6, 7]), array([8, 9])]

In [100]:
splitted_array[0],splitted_array[1],splitted_array[2]

(array([1, 2, 4]), array([5, 6, 7]), array([8, 9]))

## NumPy Searching Arrays

### Searching Arrays in NumPy
    1. Searching means finding a specific value in an array.
    2. NumPy can return the index positions of matching elements.
    3. The where() function is used to search arrays.
    4. where() returns the indexes where the condition is true.

In [104]:
arr = np.array([4,2,4,5,4,7,4,9])
x = np.where(arr == 4)
print(x)

(array([0, 2, 4, 6]),)


In [105]:
x = np.where(arr%2 == 0)
print(x)

(array([0, 1, 2, 4, 6]),)


In [106]:
x = np.where(arr%3 == 1)
print(x)

(array([0, 2, 4, 5, 6]),)


# Searchsort

In [111]:
arr = np.array([10, 20, 30])
idx = np.searchsorted(arr, 45)
print(idx)  # Output: 1 (fits between index 0 and index 1)


3


In [109]:
np.searchsorted([11,12,13,14,15], 13, side='right')

np.int64(3)

## Sorting Arrays in NumPy
    1. Sorting means arranging elements in a specific order.
    2. The order can be numeric or alphabetical.
    3. Sorting can be in ascending or descending order.
    4. NumPy provides the sort() function to sort arrays.
    4. sort() returns the array elements in sorted order.

In [114]:
a = np.array([3,2,4,5,1,9,0])
print(np.sort(a))

[0 1 2 3 4 5 9]


In [115]:
a = np.array(['beta','alpha','man','cat'])
np.sort(a)

array(['alpha', 'beta', 'cat', 'man'], dtype='<U5')

# common ways to create a array

In [118]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [119]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [120]:
a = np.zeros((3,3,5))
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [121]:
one = np.ones((2,3,4))

In [122]:
one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [124]:
one = np.empty((2,3,4))
one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [126]:
arrange = np.arange(1,10) # arange(start,stop,step)
arrange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
arrange = np.arange(0,50,5) # arange(start,stop,step)
arrange

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [129]:
linspace = np.linspace(0,1)
linspace

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [130]:
linspace = np.linspace(0,10,5)
linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Random

In [131]:
from numpy import random
print(random.rand())

0.6379302300459594


In [136]:
print(random.randint(100))


3


In [137]:
print(random.randint(100,size=5))


[30 53  1 78 16]


In [141]:
x= random.randint(100,size=(5))
x


array([72, 92, 50,  6, 28])

In [146]:
print(random.choice(x))

50


In [ ]:
arr1 =
arr2 =

In [ ]:
arr1.add(arr2)
arr1.subtract(arr2)
arr1.multiply(arr2)
arr1.mod(arr2)
