# Comprehensive NumPy Assignment

**Python for Data Science – NumPy Practice Assignment**

## Instructions
- Use only the NumPy library unless specified otherwise.
- Write clean and well-commented code.
- Display outputs for every question.
- Attempt all questions.
- Explain the logic behind your solutions wherever possible.

## Part 1: Introduction to NumPy

Q1. Import NumPy and display its version.

In [2]:
import numpy as np
print(f"NumPy Version: {np.__version__}")

NumPy Version: 2.4.6


Q2. Create arrays: (1) 1-D array from 1 to 10, (2) 3x4 zeros, (3) 3x3 ones, (4) identity matrix of size 5, (5) even numbers from 2 to 20.

In [7]:
arr_1d = np.arange(1, 11)
print("1-D Array (1 to 10):\n", arr_1d, "\n")

zeros_matrix = np.zeros((3, 4))
print("3x4 Zeros Matrix:\n", zeros_matrix, "\n")

ones_matrix = np.ones((3, 3))
print("3x3 Ones Matrix:\n", ones_matrix, "\n")

identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix, "\n")

even_arr = np.arange(2, 21, 2)
print("Even Numbers (2 to 20):\n", even_arr)


1-D Array (1 to 10):
 [ 1  2  3  4  5  6  7  8  9 10] 

3x4 Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

3x3 Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

Even Numbers (2 to 20):
 [ 2  4  6  8 10 12 14 16 18 20]


Q3. Create arrays using np.arange(), np.linspace(), np.random.rand(), np.random.randint(), and np.full(). Explain the differences.

In [ ]:
arr_arange = np.arange(0, 10, 2)           
arr_linspace = np.linspace(0, 1, 5)        
arr_rand = np.random.rand(2, 2)            
arr_randint = np.random.randint(1, 100, 5)  
arr_full = np.full((2, 3), 7)            

print(f"np.arange (Step-based sequence): {arr_arange}")
print(f"np.linspace (Evenly split scale): {arr_linspace}")
print(f"np.random.rand (Continuous floats):\n {arr_rand}")
print(f"np.random.randint (Discrete bounds): {arr_randint}")
print(f"np.full (Constant scalar allocation):\n {arr_full}")

np.arange (Step-based sequence): [0 2 4 6 8]
np.linspace (Evenly split scale): [0.   0.25 0.5  0.75 1.  ]
np.random.rand (Continuous floats):
 [[0.44250476 0.52090588]
 [0.71189395 0.42835321]]
np.random.randint (Discrete bounds): [18 51 33 97 60]
np.full (Constant scalar allocation):
 [[7 7 7]
 [7 7 7]]


## Array Attributes

Q4. Given arr = np.array([[10,20,30],[40,50,60],[70,80,90]]), find shape, size, dimension, dtype, itemsize, and memory occupied.

In [10]:
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

print(f"Shape (Dimensional Layout): {arr.shape}")
print(f"Size (Total elements cached): {arr.size}")
print(f"Dimension (Tensor rank/Axes count): {arr.ndim}")
print(f"Data Type (Precision mapping): {arr.dtype}")
print(f"Itemsize (Bytes consumed per single cell): {arr.itemsize} bytes")
print(f"Memory Occupied (Total sequence allocation footprint): {arr.nbytes} bytes")

Shape (Dimensional Layout): (3, 3)
Size (Total elements cached): 9
Dimension (Tensor rank/Axes count): 2
Data Type (Precision mapping): int64
Itemsize (Bytes consumed per single cell): 8 bytes
Memory Occupied (Total sequence allocation footprint): 72 bytes


Q5. Convert the array into float, integer, and boolean types.

In [11]:
float_version = arr.astype(np.float64)
int_version = float_version.astype(np.int32)
bool_version = arr.astype(bool)

print("Casted Float Representation:\n", float_version, "\n")
print("Casted Integer Representation:\n", int_version, "\n")
print("Boolean Mask Mapping (Truth evaluation over elements):\n", bool_version)

Casted Float Representation:
 [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]] 

Casted Integer Representation:
 [[10 20 30]
 [40 50 60]
 [70 80 90]] 

Boolean Mask Mapping (Truth evaluation over elements):
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Part 3: Indexing and Slicing

###### Creata a 4x4x2 array and display the elements, rows and columns

In [12]:
arr_3d = np.arange(1, 33).reshape(4, 4, 2)

print("Full Multi-Dimensional Elements structure:\n", arr_3d, "\n")
print("Extracting Block 0, First Row:\n", arr_3d[0, 0, :])
print("Extracting Block 0, First Column:\n", arr_3d[0, :, 0])


Full Multi-Dimensional Elements structure:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]]] 

Extracting Block 0, First Row:
 [1 2]
Extracting Block 0, First Column:
 [1 3 5 7]


Q7. Reverse the entire array, rows, and columns.

In [13]:
rev_entire = arr_3d[::-1, ::-1, ::-1]
rev_rows = arr_3d[:, ::-1, :]
rev_cols = arr_3d[:, :, ::-1]

print("Completely Reversed Layout Matrix:\n", rev_entire)


Completely Reversed Layout Matrix:
 [[[32 31]
  [30 29]
  [28 27]
  [26 25]]

 [[24 23]
  [22 21]
  [20 19]
  [18 17]]

 [[16 15]
  [14 13]
  [12 11]
  [10  9]]

 [[ 8  7]
  [ 6  5]
  [ 4  3]
  [ 2  1]]]


Q8. Replace values greater than 30 with 0.

In [14]:
target_arr = np.array([10, 25, 35, 40, 15, 50])
target_arr[target_arr > 30] = 0
print("Mask Filtered Modifed Array:\n", target_arr)

Mask Filtered Modifed Array:
 [10 25  0  0 15  0]


## Part 4: Reshaping and Flattening

Q9. Create an array from 1 to 24 and reshape it into different dimensions. Compare flatten() and ravel().

In [15]:
base_24 = np.arange(1, 25)

matrix_2d = base_24.reshape(4, 6)
tensor_3d = base_24.reshape(2, 3, 4)

flat_copied = matrix_2d.flatten()
flat_viewed = matrix_2d.ravel()

flat_copied[0] = 999
print("Original Matrix after modifying flatten() copy (No Change):", matrix_2d[0, 0])

flat_viewed[0] = 999
print("Original Matrix after modifying ravel() view (Mutated):", matrix_2d[0, 0])


Original Matrix after modifying flatten() copy (No Change): 1
Original Matrix after modifying ravel() view (Mutated): 999


Q10. Demonstrate transpose(), swapaxes(), and reshape(-1).

In [16]:
sample_matrix = np.arange(1, 7).reshape(2, 3)

print("Original Array Shape (2,3):\n", sample_matrix, "\n")
print("Transposed Layout Shape (3,2):\n", sample_matrix.T, "\n")
print("Swapping Axes explicitly:\n", np.swapaxes(sample_matrix, 0, 1), "\n")
print("Flattened downstream via automatic sizing token reshape(-1):\n", sample_matrix.reshape(-1))

Original Array Shape (2,3):
 [[1 2 3]
 [4 5 6]] 

Transposed Layout Shape (3,2):
 [[1 4]
 [2 5]
 [3 6]] 

Swapping Axes explicitly:
 [[1 4]
 [2 5]
 [3 6]] 

Flattened downstream via automatic sizing token reshape(-1):
 [1 2 3 4 5 6]


## Part 5: Mathematical Operations

Q11. Perform arithmetic operations between arrays.

In [ ]:
m1 = np.array([10, 20, 30])
m2 = np.array([1, 2, 3])

print("Vector Add:", m1 + m2)
print("Vector Sub:", m1 - m2)
print("Vector Mul:", m1 * m2)
print("Vector Div:", m1 / m2)

Q12. Find square root, exponential, logarithm, sine, cosine, and tangent values.

In [ ]:
calc_vectors = np.array([1.0, 2.0, 3.0])

print("Square Root evaluation:", np.sqrt(calc_vectors))
print("Exponential evaluation:", np.exp(calc_vectors))
print("Natural Log evaluation:", np.log(calc_vectors))
print("Trig Sine map values:", np.sin(calc_vectors))
print("Trig Cosine map values:", np.cos(calc_vectors))
print("Trig Tangent map values:", np.tan(calc_vectors))

Q13. Compare arrays using relational operators.

In [ ]:
v1 = np.array([5, 12, 18])
v2 = np.array([10, 12, 3])

print("Element-wise Greater Than comparison:", v1 > v2)
print("Element-wise Strict Equivalence check:", v1 == v2)

Q14. Perform Dot product of multi dimensional array

In [3]:
mat_A = np.array([[1, 2], [3, 4]])
mat_B = np.array([[5, 6], [7, 8]])
dot_res = np.dot(mat_A, mat_B)
print("Algebraic Dot Product Matrix Matrix result:\n", dot_res)

Algebraic Dot Product Matrix Matrix result:
 [[19 22]
 [43 50]]


## Part 7: Aggregation Functions

Q15. Find sum, mean, median, standard deviation, variance, maximum, and minimum.

In [4]:
agg_pool = np.array([12, 45, 7, 23, 89, 34])

print("Sum total:", np.sum(agg_pool))
print("Arithmetic Mean:", np.mean(agg_pool))
print("Median split:", np.median(agg_pool))
print("Standard Deviation dispersion:", np.std(agg_pool))
print("Variance scale calculation:", np.var(agg_pool))
print("Maximum boundary peak:", np.max(agg_pool))
print("Minimum bound valley:", np.min(agg_pool))

Sum total: 210
Arithmetic Mean: 35.0
Median split: 28.5
Standard Deviation dispersion: 27.30689778548026
Variance scale calculation: 745.6666666666666
Maximum boundary peak: 89
Minimum bound valley: 7


Q16. Find row-wise and column-wise statistics.

In [5]:
stat_matrix = np.array([[1, 5, 9], [10, 2, 6]])
print("Column-wise Maximum bounds (axis=0):", np.max(stat_matrix, axis=0))
print("Row-wise Mean calculations (axis=1):", np.mean(stat_matrix, axis=1))

Column-wise Maximum bounds (axis=0): [10  5  9]
Row-wise Mean calculations (axis=1): [5. 6.]


Q17. Find cumulative sum and cumulative product.

In [6]:
series_data = np.array([1, 3, 6, 10])

print("Running Cumulative Sum sequence:", np.cumsum(series_data))
print("Running Cumulative Product sequence:", np.cumprod(series_data))

Running Cumulative Sum sequence: [ 1  4 10 20]
Running Cumulative Product sequence: [  1   3  18 180]


## Part 8: Sorting and Searching

Q18. Sort arrays and find indices and elements satisfying conditions.

In [7]:
unorganized = np.array([14, 2, 73, 19, 44])
print("Sorted Array Output:", np.sort(unorganized))

match_indices = np.where(unorganized > 15)
print("Indices evaluating higher than 15:", match_indices[0])
print("Extracted elements matching logic:", unorganized[unorganized > 15])

Sorted Array Output: [ 2 14 19 44 73]
Indices evaluating higher than 15: [2 3 4]
Extracted elements matching logic: [73 19 44]


Q19. Find unique elements and their frequencies.

In [9]:
repeated_pool = np.array([1, 2, 2, 3, 4, 4, 5])
vals, frequencies = np.unique(repeated_pool, return_counts=True)
print("Discovered Unique Array items:", vals)
print("Frequency footprint trace counts:", frequencies)


Discovered Unique Array items: [1 2 3 4 5]
Frequency footprint trace counts: [1 2 1 2 1]


## Part 9: Stacking and Splitting

Q20. Demonstrate stacking methods.

In [10]:
block_left = np.array([[1, 2], [3, 4]])
block_right = np.array([[5, 6], [7, 8]])

print("Vertical Layout Stack (vstack):\n", np.vstack((block_left, block_right)), "\n")
print("Horizontal Layout Stack (hstack):\n", np.hstack((block_left, block_right)), "\n")

Vertical Layout Stack (vstack):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

Horizontal Layout Stack (hstack):
 [[1 2 5 6]
 [3 4 7 8]] 



Q21. Split arrays into equal parts.

In [ ]:
divisible_arr = np.arange(12)

# Performing uniform slices across sequence items
segments = np.split(divisible_arr, 3)
for idx, seg in enumerate(segments):
    print(f"Segment slice index [{idx}]: {seg}")

## Part 10: Random Module

Q22. Generate random numbers and matrices.

In [11]:
np.random.seed(42)
rand_scalar = np.random.rand()
random_matrix = np.random.randint(10, 50, size=(3, 3))

print(f"Random Scalar generated: {rand_scalar}")
print("Random Structured Matrix:\n", random_matrix)

Random Scalar generated: 0.3745401188473625
Random Structured Matrix:
 [[38 24 17]
 [30 48 28]
 [32 20 20]]


Q23. Simulate rolling a die 100 times and analyze frequencies.

In [12]:
die_trials = np.random.randint(1, 7, size=100)
faces, counts = np.unique(die_trials, return_counts=True)

print("Distribution breakdown for 100 trials:")
for face, count in zip(faces, counts):
    print(f"Dice Face Vector [{face}] -> Occurred {count} times")

Distribution breakdown for 100 trials:
Dice Face Vector [1] -> Occurred 16 times
Dice Face Vector [2] -> Occurred 18 times
Dice Face Vector [3] -> Occurred 9 times
Dice Face Vector [4] -> Occurred 25 times
Dice Face Vector [5] -> Occurred 15 times
Dice Face Vector [6] -> Occurred 17 times


## Part 11: Boolean Masking and Filtering

Q24. Extract values based on conditions.

In [13]:
eval_domain = np.array([12, 45, 67, 23, 89, 90, 11])
composite_mask = (eval_domain > 20) & (eval_domain < 80)
print("Extracted elements matching strict range parameters:", eval_domain[composite_mask])

Extracted elements matching strict range parameters: [45 67 23]


Q25. Replace odd numbers with -1.

In [14]:
sequence_source = np.arange(1, 11)


sequence_source[sequence_source % 2 != 0] = -1
print("Transformed Odd Array mapping sequence:\n", sequence_source)

Transformed Odd Array mapping sequence:
 [-1  2 -1  4 -1  6 -1  8 -1 10]


## Part 12: Missing Values

Q26. Detect and replace missing values.

In [15]:
experimental_metrics = np.array([10.5, np.nan, 45.2, np.nan, 3.0])

print("Boolean mapping trace for NaN holes:", np.isnan(experimental_metrics))


experimental_metrics[np.isnan(experimental_metrics)] = 0.0
print("Cleaned array payload output:\n", experimental_metrics)

Boolean mapping trace for NaN holes: [False  True False  True False]
Cleaned array payload output:
 [10.5  0.  45.2  0.   3. ]


## Part 13: Linear Algebra

Q27. Perform matrix operations.

In [16]:
X_mat = np.array([[1, 2], [3, 4]])
Y_mat = np.array([[2, 0], [1, 2]])

print("Matrix Summation mapping:\n", X_mat + Y_mat)
print("Matrix Multi-dot transformation alignment:\n", X_mat @ Y_mat)

Matrix Summation mapping:
 [[3 2]
 [4 6]]
Matrix Multi-dot transformation alignment:
 [[ 4  4]
 [10  8]]


Q28. Find determinant, inverse, transpose, eigenvalues, and eigenvectors.

In [17]:
linear_matrix = np.array([[3, 2], [1, 4]])

print("Matrix Transpose:\n", linear_matrix.T, "\n")
print("Scalar Determinant metric:", np.linalg.det(linear_matrix), "\n")
print("Matrix Inverse configuration:\n", np.linalg.inv(linear_matrix), "\n")

eigen_values, eigen_vectors = np.linalg.eig(linear_matrix)
print("Extracted Characteristic Roots (Eigenvalues):", eigen_values)
print("Extracted Characteristic Basis Vectors (Eigenvectors):\n", eigen_vectors)

Matrix Transpose:
 [[3 1]
 [2 4]] 

Scalar Determinant metric: 10.000000000000002 

Matrix Inverse configuration:
 [[ 0.4 -0.2]
 [-0.1  0.3]] 

Extracted Characteristic Roots (Eigenvalues): [2. 5.]
Extracted Characteristic Basis Vectors (Eigenvectors):
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Q29. Solve a system of linear equations using NumPy.

In [19]:

# Systems of Equations mapping format: Coefficient matrix (A) * variable equals Constants (b)
# Equations mapped below:  2x + 3y = 8  and  1x + 2y = 5
A_coeffs = np.array([[2, 3], [1, 2]])
b_constants = np.array([8, 5])

unknown_solution = np.linalg.solve(A_coeffs, b_constants)
print(f"System Root Solutions evaluated -> x = {unknown_solution[0]:.4f}, y = {unknown_solution[1]:.4f}")

System Root Solutions evaluated -> x = 1.0000, y = 2.0000


## Part 14: Advanced NumPy

Q30. Demonstrate fancy indexing, boolean indexing, where(), argmax(), argmin(), and argsort().

In [20]:
advanced_pool = np.array([20, 80, 40, 10, 50])

print("Fancy Indexing extraction (targets index position 0, 1, 4):", advanced_pool[[0, 1, 4]])
print("Boolean Indexing filter extraction:", advanced_pool[advanced_pool < 45])
print("Locating index fields via where matching:", np.where(advanced_pool == 40)[0])
print("Argmax position tracking index:", np.argmax(advanced_pool))
print("Argmin position tracking index:", np.argmin(advanced_pool))
print("Argsort sequencing index mapping trace:", np.argsort(advanced_pool))

Fancy Indexing extraction (targets index position 0, 1, 4): [20 80 50]
Boolean Indexing filter extraction: [20 40 10]
Locating index fields via where matching: [2]
Argmax position tracking index: 1
Argmin position tracking index: 3
Argsort sequencing index mapping trace: [3 0 2 4 1]


Q31. Use tile(), repeat(), clip(), and diag().

In [21]:
base_seed = np.array([1, 5])

print("Tiling replication mapping:", np.tile(base_seed, 3))
print("Repeating individual item elements sequentially:", np.repeat(base_seed, 3))

clipping_targets = np.array([5, 12, 45, 2, 28])
print("Clamped tracking boundaries via clipping (Bounds 10 to 30):", np.clip(clipping_targets, 10, 30))

matrix_space = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Diagonal axis trace extraction mapping:", np.diag(matrix_space))

Tiling replication mapping: [1 5 1 5 1 5]
Repeating individual item elements sequentially: [1 1 1 5 5 5]
Clamped tracking boundaries via clipping (Bounds 10 to 30): [10 12 30 10 28]
Diagonal axis trace extraction mapping: [1 5 9]


Q32. Create a checkerboard pattern.

In [22]:
checkerboard = np.zeros((8, 8), dtype=np.int32)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q33. Write a line of code to extract the inner 2×2 submatrix (excluding the border rows and columns).

In [23]:
outer_4x4 = np.arange(1, 17).reshape(4, 4)
inner_2x2 = outer_4x4[1:-1, 1:-1]
print("Cropped Internal Submatrix :\n", inner_2x2)

Cropped Internal Submatrix :
 [[ 6  7]
 [10 11]]


Q34. Reshape a 1D array of 12 elements (from Step 4) into a 3×4 2D matrix.

In [24]:
source_12 = np.arange(12)
matrix_3x4 = source_12.reshape(3, 4)
print("Reshaped 3x4 Matrix:\n", matrix_3x4)

Reshaped 3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Q35 Create a 3×3 identity matrix.

In [25]:
matrix_identity_3x3 = np.eye(3)
print("3x3 Identity matrix:\n", matrix_identity_3x3)

3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q35. Stack two identical 2×2 arrays of ones vertically.

In [26]:
ones_2x2 = np.ones((2, 2))
vertical_stacked_ones = np.vstack((ones_2x2, ones_2x2))
print("Vertically Stacked Ones:\n", vertical_stacked_ones)

Vertically Stacked Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Q36. Create Matrix A with dimensions 2×3 and Matrix B with dimensions 3×2.

In [27]:
matrix_A = np.arange(1, 7).reshape(2, 3)
matrix_B = np.arange(1, 7).reshape(3, 2)

print("Matrix A (2x3):\n", matrix_A)
print("Matrix B (3x2):\n", matrix_B)

Matrix A (2x3):
 [[1 2 3]
 [4 5 6]]
Matrix B (3x2):
 [[1 2]
 [3 4]
 [5 6]]


Q37. Perform a matrix multiplication (A × B) to yield a 2×2 matrix result.

In [29]:
matrix_multiplication_result = matrix_A @ matrix_B
print("Matrix Multiplication (A x B) Resulting 2x2 Matrix:\n", matrix_multiplication_result)

Matrix Multiplication (A x B) Resulting 2x2 Matrix:
 [[22 28]
 [49 64]]


# Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [ ]:
# Complete the following code in order to add the vector v to each row of a matrix x:
# x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
# v = np.array([1,0,1])
# y = np.zeros(x.shape)
# for i in range(x.shape[0]):
#     for j in range(x.shape[1]):
#         y[i,j] =


x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1,0,1])
y = np.zeros(x.shape)

# Loop execution to manually handle dimension stepping mapping offsets
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i,j] = x[i,j] + v[j]

print("Loop Implementation Output Array:\n", y)


#(The NumPy Broadcast way)
y_efficient = x + v
print("\nVectorized Broadcasting Output Array:\n", y_efficient)

Loop Implementation Output Array:
 [[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]
